[env:bluepill_f103c8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
monitor_speed = 115200
build_flags =
  -D HSE_VALUE=8000000U
  -I../../freertos
  -I../../lib/FreeRTOS-Kernel/portable/GCC/ARM_CM3
lib_extra_dirs =
  ../../lib
